version: '3'

services:
  web:
    build: .
    image: node-api
    container_name: bindclientsmercafacil_nodejs_1
    ports:
      - 8000:5000
    environment:
      -  DATABASE_HOST_MYSQL=mysqlconnection
      -  DATABASE_HOST_POSTGRES=pgconnection
      -  POSTGRES_USER=admin
      -  POSTGRES_PASSWORD=admin
      -  POSTGRES_PORT=5432
      -  POSTGRES_DATABASE=postgres
      -  MYSQL_USER=admin
      -  MYSQL_PASSWORD=admin
      -  MYSQL_PORT=3306
      -  MYSQL_DATABASE=admin
      -  JWT_SECRET_KEY=secretkey
    links:
      - "mysql"
      - "postgresql"
    
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=admin
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
    hostname: "mysqlconnection"
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password

  postgresql:
    image: postgres
    hostname: "pgconnection"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: "admin"
      POSTGRES_USER: "admin"
